### PR TITLE
Update example

### PR DESCRIPTION
**Pull request by ghoneycutt**
Fixes #303

### CODE REVIEW

**Comment by ghoneycutt** [comment]
Just took the old PR #303 and fixed the style.

**Comment by ekohl** [comment]
I wonder how the tests are broken by this. Is master already broken?

**Comment by ghoneycutt** [comment]
@ekohl Looks like. Could you approve this one as it passes lint and as an example would not have an effect on spec tests?

**Comment by ekohl** [comment]
Makes sense. Thanks!

**Pull request merged**
