### PR TITLE
Release checks fixes

### PR DESCRIPTION
**Pull request by maage**
Small fixes to make rake release_checks pass and silence warnings and so on. I run my tests in Centos 7 and needed to fix some stuff too.

This should fix #101 and #112 .

### CODE REVIEW

**Comment by juniorsysadmin** [comment]
After a module like this one has been moved across to voxpupuli we normally do a modulesync using our own modulesync_config defaults (Gemfile, Rakefile etc). After this is done, you'll need to rebase and drop your Gemfile changes (unless it's something that should already be a default). If you need changes merged urgently, the best thing to do would be separate PRs that individually address the issues that you mentioned. Thanks!

**Comment by bastelfreak** [comment]
This is a lot of effort. I will merge this + do a modulesync afterwards. @maage Can you check our modulesync later just in case we kill any changes you made and need?

**Comment by bastelfreak** [comment]
@maage new modulesync run happens in https://github.com/voxpupuli/puppet-selinux/pull/116

**Comment by bastelfreak** [comment]
okay I just realised that you did a modulesync here :+1:

**Comment by maage** [comment]
Thanks. Sorry about not communicating, I did not get pass from travis until I had to take last test. I'm not sure if my modulesync work is up to Vox Pupuli standards but at least many parts are what was there. I tried to save parts that were extended originally like extra lints and testing stuff.

**Pull request merged**
