### PR TITLE
Add Debian 11 support

### PR DESCRIPTION
**Pull request by jbrnfnd**
#### Pull Request (PR) description
This PR enables support for Debian 11 by adding a yaml file, 11.yaml in the Debian subfolder
It is a straight renamed copy of 10.yaml

### CODE REVIEW

**Comment by ghoneycutt** [comment]
Thanks for the contribution! For this module to support Debian 11, it needs to be reocrded in the metadata - https://github.com/voxpupuli/puppet-selinux/blob/master/metadata.json

**Comment by smortex** [comment]
I think you can fix CI by improving:

https://github.com/voxpupuli/puppet-selinux/blob/92f1bf59c43de4e8112b6f9d6f13f36e0a4d3671/manifests/boolean.pp#L39

```diff
-  if $facts['os']['selinux']['enabled'] {
+  if facts('os.selinux.enabled') {
```

**Comment by jbrnfnd** [comment]
Hi,

From the documentation, the squared bracket syntax is also supported in Puppet 5.5
https://puppet.com/docs/puppet/5.5/lang_facts_and_builtin_vars.html#the-factsfact_name-hash
I don't know why this is failing, as the syntax is the same used as in older versions of puppet-selinux
As puppet5 is EOL since end of january 2021, why it is still in the CI workflow?
Wouldn't it be better to only support active Puppet versions?

**Comment by cmseal** [comment]
Hi.  Aside from the EOL Puppet 5 test and Puppet 5 support requested to be removed in a separate PR, is there anything else required to move this forwards?

**Comment by jbrnfnd** [comment]
Hi, due to work related things i am completely stalled here. i would like to post a pull request but don't know how.
the yml files in .github/workflows do not indicate to exclude puppet 5 in my opinion.

**Comment by ekohl** [comment]
It's because of this line:
https://github.com/voxpupuli/puppet-selinux/blob/92f1bf59c43de4e8112b6f9d6f13f36e0a4d3671/metadata.json#L58
If you update that (preferably to `>= 6.1.0`) then it should stop testing on Puppet 5.

**Comment by laser-dev-support** [comment]
Hi, any update on this PR? We really need to have it working on Debian 11.

thanks a lot

f.

**Comment by ekohl** [comment]
I opened https://github.com/voxpupuli/puppet-selinux/pull/361 & https://github.com/voxpupuli/puppet-selinux/pull/362

**Comment by ekohl** [comment]
Solved via https://github.com/voxpupuli/puppet-selinux/pull/359 instead.

**Pull request closed without merging**
