### PR TITLE
Fix type doc

### PR DESCRIPTION
**Pull request by kausar007**
Fixed `type` doc and `sx_mod_dir`.

### CODE REVIEW

**Comment by bastelfreak** [comment]
Hi @kausar007, thanks for the PR. Can you please rebase and fix the merge conflicts?

**Comment by vinzent** [comment]
obsoleted by  merged PR #150

**Comment by kausar007** [comment]
@bastelfreak Done.
@vinzent doc for param sx_mod_dir in module.pp still needs to be updated.

**Comment by bastelfreak** [comment]
thanks!

**Pull request merged**
